### ISSUE TITLE
Info request: how is node-tumblr doing?

### ISSUE THREAD

**Issue by giacecco** [meritt/node-tumblr#1]
Hi Alexey, I see you have not been updating node-tumblr for a while. Is it because it is already very robust as it is, or because you've been busy on other projects? I am asking because I was thinking of starting re-using your work intensively and would value your impressions. Thanks.

G.

**Comment by meritt** [comment]
Hey. Yes, i think current code already very robust. And of course i'm planning to continue maintenance.
